### ISSUE TITLE
Run tests on CI

### ISSUE THREAD

**Issue by vyshkov** [TheBit/browser-ui-state#6]
You should run your tests on the travis CI before build, so if it fails - then it marks you commit with X - cross icon.

**Comment by TheBit** [comment]
Yeah, of course, I just don't know yet what is the best way to organize this :).
Should I just add "test" script command inside "build" command? But I think there could be some other, more organic ways, I see there are some lifecycles, etc https://docs.npmjs.com/misc/scripts

**Comment by TheBit** [comment]
Done, example of failed commit and build:
 - https://github.com/device-hackers/browser-ui-state/commits/master (854e7cfe262e390875a55a300ec8006a3c31694d)
 - https://travis-ci.org/device-hackers/browser-ui-state/builds/289942140
